version: "3"

volumes:
  photocrate_local_postgres_data: {}
  photocrate_local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: photocrate_local_django
    container_name: photocrate_local_django
    depends_on:
      - postgres
      - elasticsearch
      - redis
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: photocrate_production_postgres
    container_name: photocrate_local_postgres
    volumes:
      - photocrate_local_postgres_data:/var/lib/postgresql/data
      - photocrate_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

  # celery:
  #   build:
  #     context: .
  #     dockerfile: ./compose/local/django/Dockerfile
  #   command: celery --app=core worker --loglevel=info
  #   volumes:
  #     - ./config:/usr/src/app
  #   depends_on:
  #     - django
  #     - redis

  redis:
    image: redis:7-alpine
