# Generated by Django 4.1.8 on 2023-05-09 19:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="imageupload",
            name="public_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
