# Generated by Django 4.1.8 on 2023-05-09 21:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("photos", "0002_imageupload_public_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imageupload",
            name="image",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="image"
            ),
        ),
    ]
