# Generated by Django 4.1.8 on 2023-04-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("graphics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="graphic",
            name="url",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
